version: 2.1
jobs:
  build:
    machine:
      image: apon77/aosp:cirrus
    steps:
      - checkout
      - run:
          name: "Init repo"
          command: echo y | ./repo init --depth=1 -u https://github.com/Evolution-X/manifest -b tiramisu
      - run:
          name: "Sync Repo"
          command: ./repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: "Sync Device tree"
          command: git clone --depth=1 https://github.com/DevAdalat/android_device_xiaomi_gauguin device/xiaomi/gauguin
      - run:
          name: "Setup Vendor"
          command: bash device/xiaomi/gauguin/vendorsetup.sh
      - run:
          name: "Setup env"
          command: source build/envsetup.sh
      - run:
          name: "Lunch"
          command: lunch evolution_gauguin-userdebug
      - run:
          name: "Use USE_CCACHE"
          command: export USE_CCACHE=1
      - run:
          name: "Setup CCACHE Path"
          command: export CCACHE_EXEC=/usr/bin/ccache
      - run:
          name: "Setup CCACHE Size"
          command: ccache -M 20G
      - run:
          name: "Enable CCACHE Compresson"
          command: ccache -o compression=true
      - run:
          name: "Build"
          command: lunch evolution_gauguin-userdebug && mka evolution
      - run:
          name: "List Files"
          command: ls $OUT
 

